# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Bouncey Blob iOS' do
   pod 'Mixpanel'
end

target 'Jump Android' do

end

target 'Jump Mac' do

end

