# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

  use_frameworks!


target 'Bouncey Blob iOS' do
pod 'Mixpanel'
end

target 'Bouncey Blob Android' do

end

target 'Bouncey Blob Mac' do

end

